name: 🐞 Report a bug with a community-authored plugin
description: Support is provided on a *best-effort basis* by the community
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug!  
        This repository contains **community-authored plugins for SquaredUp**.

        Please note:
        - This plugin is **not officially supported by SquaredUp**
        - Support is provided on a **best-effort basis** by the community and plugin author

        The more detail you provide, the more likely it is that someone can help.

  - type: input
    id: plugin-name
    attributes:
      label: Plugin name
      description: Name of the SquaredUp plugin for which the issue occurs
      placeholder: e.g. Cloudflare
    validations:
      required: true

  - type: input
    id: plugin-version
    attributes:
      label: Plugin version
      description: Version or commit hash of the plugin
      placeholder: e.g. v1
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to...
        2. Configure the plugin with...
        3. View the dashboard...
        4. See error
    validations:
      required: true

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmation
      options:
        - label: I have checked that this issue has not already been reported
          required: true
        - label: I understand this is a community-supported plugin
          required: true
