name: ✨ Feature request
description: Suggest a new feature or datastream for a community-authored plugin
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an enhancement!

        This repository contains **community-authored plugins for SquaredUp**.
        Feature requests are welcomed, but are implemented on a **best-effort basis**
        by the community and plugin authors.

        Please be as specific as possible about what you'd like to see.

  - type: input
    id: plugin-name
    attributes:
      label: Plugin name
      description: Name of the SquaredUp plugin this request applies to
      placeholder: e.g. Cloudflare
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature type
      description: What kind of feature are you requesting?
      options:
        - New datastream
        - Enhancement to existing datastream
        - Enhancement to object indexing
        - Enhancement to plugin configuration
        - Documentation improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: request-description
    attributes:
      label: Request description
      description: A clear and concise description of the feature request
      placeholder: What are you requesting?
    validations:
      required: true

  - type: checkboxes
    id: confirmations
    attributes:
      label: Confirmation
      options:
        - label: I have checked that this feature has not already been requested
          required: true
        - label: I understand this is a community-supported plugin and not an official SquaredUp feature
          required: true
